- hosts: all
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_161"
    java_archive: "{{download_folder}}/jdk-8u161-linux-x64.tar.gz"

    jenkins_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    jenkins_folder: /etc/yum.repos.d/jenkins.repo
    jenkins_rpm: "{{jenkins_url}}.io.key"


  tasks:
   - name: Install wget
     yum:
       name: wget
       state: latest

   - name: Download Java
     command: "wget -q -O {{java_archive}} --no-cookies --no-check-certificate --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie' {{download_url}}"
   
   - name: Unpack archive
     command: tar xzf /opt/jdk-8u161-linux-x64.tar.gz
     
   - name: selected java version
     alternatives:
        name: java
        path: /opt/jdk1.8.0_161/bin/java
        link: /usr/bin/java

   - name: selected java version
     alternatives:
        name: jar
        path: /opt/jdk1.8.0_161/bin/jar
        link: /usr/bin/jar

   - name: selected java version
     alternatives:
        name: javec
        path: /opt/jdk1.8.0_161/bin/javac
        link: /usr/bin/javac

   
   - name: Setup Java Environment Variables
     command: export JAVA_HOME=/opt/jdk1.8.0_161 | export JRE_HOME=/opt/jdk1.8.0_161/jre | export PATH=$PATH:/opt/jdk1.8.0_161/bin:/opt/jdk1.8.0_161/jre/bin
     
   - name: Install Git
     yum: 
       name: git 
       state: latest
     
   - name: Download Jenkins Repo
     command: wget -O {{jenkins_folder}} {{jenkins_url}}

   - name: rpm install
     command: rpm --import {{jenkins_rpm}}

   - name: Install Jenkins
     yum:
       name: jenkins
       state: latest
     notify: service jenkins
   
   
  handlers:
   - name: service jenkins
     service:
           name=jenkins
           state=started
           enabled=True



