- hosts: web

  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
    java_path: /usr/java/
    java_name: "{{java_path}}/jdk1.8.0_161"
    java_archive: /usr/java/jdk-8u161-linux-x64.rpm

    jenkins_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    jenkins_folder: /etc/yum.repos.d/jenkins.repo
    jenkins_rpm: https://jenkins-ci.org/redhat/jenkins-ci.org.key


  tasks:
   - name: Install Java
     yum:
      name: java
      state: latest
 
   - name: Install Git
     yum: 
       name: git 
       state: latest
     
   - name: Download Jenkins Repo
     get_url:
        url: "{{jenkins_url}}"
        dest: "{{jenkins_folder}}"

   - name: rpm import
     rpm_key:
       key: "{{jenkins_rpm}}"
       state: present

   - name: Install Jenkins
     yum:
       name: jenkins
       state: latest
     notify: service jenkins
   
   
  handlers:
   - name: service jenkins
     service:
           name=jenkins
           state=started
           enabled=True



