- hosts: web
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
    download_folder: /opt
    java_path: /usr/java/
    java_name: "{{java_path}}/jdk1.8.0_161"
    java_archive: "{{java_path}}/jdk-8u161-linux-x64.rpm"

    jenkins_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    jenkins_folder: /etc/yum.repos.d/jenkins.repo
    jenkins_rpm: "{{jenkins_url}}.io.key"


  tasks:
   - name: make dir
     file:
       path: /usr/java
       state: directory
       mode: 755

   - name: Download Java JDK
     get_url:
       url: "{{download_url}}"
       dest: "{{java_archive}}"

   - name: Unpack archive
     yum:
       name: "{{java_archive}}"
       state: installed

   - name: selected java version
     alternatives:
        name: java
        path: "{{java_path}}/jdk1.8.0_161/bin/java"
        link: /usr/bin/java

   - name: selected jar version
     alternatives:
        name: jar
        path: "{{java_path}}/jdk1.8.0_161/bin/jar"
        link: /usr/bin/jar

   - name: selected javac version
     alternatives:
        name: javec
        path: "{{java_path}}/jdk1.8.0_161/bin/javac"
        link: /usr/bin/javac
     environment:
        JAVA_HOME: "{{java_path}}/jdk1.8.0_161"
        JRE_HOME: "{{java_path}}/jdk1.8.0_161/jre"
        PATH: $PATH:"{{java_path}}/jdk1.8.0_161/bin:{{java_path}}/jdk1.8.0_161/jre/bin"
  
   - name: Install Git
     yum: 
       name: git 
       state: latest
     
   - name: Download Jenkins Repo
     get_url:
        url: "{{jenkins_url}}"
        dest: "{{jenkins_folder}}"

   - name: rpm import
     shell: rpm --import {{jenkins_rpm}}

   - name: Install Jenkins
     yum:
       name: jenkins
       state: latest
     notify: service jenkins
   
   
  handlers:
   - name: service jenkins
     service:
           name=jenkins
           state=started
           enabled=True



